# Netlify Build Settings for a Vite/React Project

[build]
 
  command = "npm run build"
 
  publish = "dist"

  
  [build.environment]
    NODE_VERSION = "22.17.0"
 
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
